# Site Author
author:
  name             : "Peter Varney"
  email            : "email@address.com"

# Collections
collections:
  podcast:
    output: true
    permalink: /:collection/:year-:month-:day-:title

