# Site Author
author:
  name             : "Peter Varney"
  email            : "email@address.com"

# Collections
collections:
  podcast:
    gitcast: true
    title: "Cast Collextion Example"
    output: true
    permalink: /:collection/:year-:month-:day-:title/

