# Site Author
author:
  name             : "John Doe"
  email            : "email@address.com"

# Collections
collections:
  podcast:
    gitcast: true
    output: true
    permalink: /:collection/:year-:month-:day-:title/
