# Site Author
author:
  name             : "John Doe"
  email            : "email@address.com"

# Collections
collections:
  podcast:
    gitcast: true
    cast:
      title: "Cast Collextion Example"
      #type: 'episodic'
      #explicit: 'no'
      #author:
      #  name: "Jane Doe"
      #  email: "email@address.com"
      #copyright: "2020 Doe LLC"
      #description: 'This is a podcast about testing a podcast'
    output: true
    permalink: /:collection/:year-:month-:day-:title/
