# Site Author
author:
  name             : "John Doe"
  email            : "email@address.com"

# Collections
collections:
  podcast:
    gitcast: true
    #description: 'This is a podcast about testing a podcast'
    output: true
    #permalink: pretty
    permalink: /:collection/:year-:month-:day-:title/
